### ISSUE TITLE
Configurable Thread Key

### ISSUE THREAD

**Issue by gokeefe** [jenkinsci/google-chat-notification-plugin#19]
Furthur to the discussion in #6, I'd really like to be able to choose the thread key... either JOB_NAME or BUILD_TAG. In my jobs I tend to have multiple notifications for when a build is started, pushing, finished, and final status, and it ends up being kind of ugly where there are multiple builds tagged onto a single thread. A configurable thread key, perhaps just a drop down list, would help customize it to a particular preference.

**Comment by Ryudo302** [comment]
Hi @gokeefe!

Version 1.5 now supports configurable thread keys (https://github.com/jenkinsci/google-chat-notification-plugin/pull/30).

Do you still need to use variables as thread keys?

**Comment by gpflaum** [comment]
Configurable thread keys aren't working because threading is currently broken: #40

**Comment by Ryudo302** [comment]
> Configurable thread keys aren't working because threading is currently broken: #40

I found that the problem here is specifically to the in-line threaded spaces, which became the default behavior since March this year: [All newly created spaces in Google Chat will be in-line threaded beginning March 13, 2023](http://workspaceupdates.googleblog.com/2023/02/new-google-chat-spaces-will-be-in-line-threaded.html). This issue don't affect spaces organized by topics.

Anyway, #40 is on the way to be fixed.
